[package]
name = "assempy"
version = "0.1.0"
authors = ["coolreader18 <33094578+coolreader18@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rustpython-parser = "0.1"
thiserror = "1.0"
parity-wasm = "0.41"
num-traits = "0.2"
pico-args = "0.3"
wabt = "0.9"
